logging:
    level:
        ROOT: WARN
        org.zowe.apiml: INFO
        org.zowe.apiml.enable: WARN
        org.springframework: WARN
        org.springframework.boot: WARN
        org.springdoc: WARN
        com.netflix: WARN
        com.netflix.discovery: ERROR
        com.netflix.config: ERROR
        com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
        com.netflix.discovery.DiscoveryClient: OFF
        org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
        org.apache.http.conn.ssl.DefaultHostnameVerifier: DEBUG #logs only SSLException
        javax.net.ssl: ERROR # For running with java 17

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: ${apiml.service.discoveryServiceUrls}
        region: default

apiml:
    enabled: true
    service:
        preferIpAddress: false

        serviceId: metrics-service
        title: Metrics Service.
        description: Service to display metrics for APIML services.

        discoveryServiceUrls: https://localhost:10011/eureka/

        scheme: https

        hostname: localhost
        port: 10019
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}
        contextPath: /${apiml.service.serviceId}

        homePageRelativeUrl: ${apiml.service.contextPath}
        statusPageRelativeUrl: ${apiml.service.contextPath}/application/info
        healthCheckRelativeUrl: ${apiml.service.contextPath}/application/health
        routes:
            -   gateway-url: "/ui/v1"
                service-url: ${apiml.service.contextPath}
            -   gateway-url: "/api/v1"
                service-url: ${apiml.service.contextPath}
            -   gateway-url: "/sse/v1"
                service-url: ${apiml.service.contextPath}
        apiInfo:
            -   apiId: zowe.apiml.metricsservice
                version: 1.0.0
                gatewayUrl: api/v1
                swaggerUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}${apiml.service.contextPath}/v3/api-docs
                documentationUrl: https://www.zowe.org
        catalog:
            tile:
                id: zowe
                title: Zowe Applications
                description: Applications which are part of Zowe.
                version: 1.0.0
        ssl:
            enabled: true
            verifySslCertificatesOfServices: true
            protocol: ${server.ssl.protocol}
            keyStoreType: ${server.ssl.keyStoreType}
            trustStoreType: ${server.ssl.trustStoreType}

            keyAlias: ${server.ssl.keyAlias}
            keyPassword: ${server.ssl.keyPassword}
            keyStore: ${server.ssl.keyStore}
            keyStorePassword: ${server.ssl.keyStorePassword}
            trustStore: ${server.ssl.trustStore}
            trustStorePassword: ${server.ssl.trustStorePassword}
        customMetadata:
            apiml:
                enableUrlEncodedCharacters: true
                gatewayPort: 10010
                gatewayAuthEndpoint: /gateway/api/v1/auth
                corsEnabled: false

spring:
    config:
        useLegacyProcessing: true
    cloud:
        compatibilityVerifier:
            enabled: false # Should be removed when upgrade to Spring Cloud 3.x
    application:
        name: Metrics Service
    output.ansi.enabled: always
    main:
        allow-circular-references: true

springdoc:
    pathsToMatch: /api/v1/**

server:
    port: ${apiml.service.port}
    servlet:
        contextPath: ${apiml.service.contextPath}

    ssl:
        enabled: true
        clientAuth: want
        protocol: TLS
        enabled-protocols: TLSv1.2+TLSv1.3
        ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384
        keyStoreType: PKCS12
        trustStoreType: PKCS12

        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            base-path: /application
            exposure:
                include: health, info, turbine.stream

turbine:
    aggregator:
        clusterConfig: APICATALOG,CACHINGSERVICE,GATEWAY,DISCOVERY # uppercase serviceId
    appConfig: apicatalog,cachingservice,gateway,discovery # lowercase serviceId

---
spring:
    profiles: debug

logging:
    level:
        ROOT: INFO
        org.zowe.apiml: DEBUG
        org.springframework: INFO
        org.apache: INFO
        org.apache.http: DEBUG
        com.netflix: INFO
        org.hibernate: INFO
        org.springframework.web.servlet.PageNotFound: WARN
        org.ehcache: INFO
        org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: INFO

---
spring:
    profiles: diag

---
spring:
    profiles: dev
    profiles.include:
        - debug
        - diag

logbackServiceName: ZWEAMS1

---
spring:
    profiles: attls

server:
    attls:
        enabled: true
    ssl:
        enabled: false

apiml:
    service:
        scheme: http

eureka:
    instance:
        nonSecurePortEnabled: true
        securePortEnabled: false
